### ISSUE TITLE
Refactor Programm.java

### ISSUE THREAD

**Issue by Noah4ever** [Noah4ever/DAO#6]
### [Programm.java](https://github.com/Noah4ever/DAO/blob/main/src/Kaufvertrag/presentationLayer/Programm.java) muss refactored werden. 
Es ist viel zu unübersichtlich. 
Vielleicht alles was mit [Ware ](https://github.com/Noah4ever/DAO/blob/1ef76a47dd50538442ea9dbf4d575db5d375149b/src/Kaufvertrag/presentationLayer/Programm.java#L397)zu tun hat in eine separate Klasse und alles was mit [Vertragspartner ](https://github.com/Noah4ever/DAO/blob/1ef76a47dd50538442ea9dbf4d575db5d375149b/src/Kaufvertrag/presentationLayer/Programm.java#L261)zu tun hat ebenfalls. Alle Funktion, die zur [Ausgabe()](https://github.com/Noah4ever/DAO/blob/1ef76a47dd50538442ea9dbf4d575db5d375149b/src/Kaufvertrag/presentationLayer/Programm.java#L150) gehören, könnten auch in eine Klasse.

**Comment by DerTyp187** [comment]
Ist halt wie um UML Diagramm.

**Comment by Noah4ever** [comment]
Mach das trotzdem mal übersichtlicher
